### ISSUE TITLE
Do you have any examples? Next.js

### ISSUE THREAD

**Issue by stevepsharpe** [sanity-io/sanity-plugin-iframe-pane#14]
Hey there

I had this working with Next.js following this guide https://www.sanity.io/guides/nextjs-live-preview

The issue I was having was that the preview mode wasn't being enabled. It looked like the redirect wasn't being followed, but I can see in the screenshot in the repo that it doesn't update.  If I opened the preview URL in a new tab it works as expected.

Do you have any examples you could share? I really want to use this, as it looks awesome :)

Best
Steve

**Comment by SimeonGriggs** [comment]
That guide has been rewritten for Studio v3, and should have some better guidance for you.
