### ISSUE TITLE
[Feature]: Loading indicator

### ISSUE THREAD

**Issue by spacedawwwg** [sanity-io/sanity-plugin-iframe-pane#19]
I'm wondering if a it might be possible to add an optional 'loading' indicator when the iframe is fetching?

We use on demand builders that take a couple of seconds to load and it'd be nice to be able to show the user something is happening within the pane rather than a blank screen (as you don't get the 'browser chrome' to inform you a request is in flight within an iframe)

**Comment by stipsan** [comment]
Shipped in https://github.com/sanity-io/sanity-plugin-iframe-pane/releases/tag/v2.2.0
