### ISSUE TITLE
Option to hide displayURL bar

### ISSUE THREAD

**Issue by SvSven** [sanity-io/sanity-plugin-iframe-pane#21]
It would be nice to have an option to hide the displayURL in the topbar of the iframe component. This makes it a bit more of a clean/seamless experience for our editors and in addition "hides" the fact we are linking to `/api/preview` with a bunch of (to them) strange query parameters (we transform the URL to a more user friendly one in Next.js).

Something simple like a `showDisplayUrl` option that defaults to `true`

```js
<Box flex={1}>
  {showDisplayUrl && (
    <Text size={0} textOverflow="ellipsis">
      {displayUrl}
    </Text>
  )}
</Box>
```

**Comment by john-rock** [comment]
I agree we need this. We just implemented this iframe plugin with a page builder type setup in our studio and I can see this cause confusion for stakeholders when they are in there.

Never worked on a Sanity plugin before but I think I may experiment with getting this feature built.
