### ISSUE TITLE
Reload.revision doesn't seem to affect anything.

### ISSUE THREAD

**Issue by nmowatt** [sanity-io/sanity-plugin-iframe-pane#72]
Not sure if this is an issue or not, but it seems like whatever I set reload.revision to, the page still reloads on every keystroke.
What I'm after is to disable auto refresh so that I need to manually click the reload button for the page to refresh.

My code look like this:

```js
S.view
  .component(Iframe)
  .options({
    url: (doc: SanityDocument) => getUrl(doc),
    showDisplayUrl: false,
    reload: {
      button: true,
      revision: false // 0 // 1000 // true
    },
  })
  .title('Preview')
```

**Comment by stipsan** [comment]
`reload.revision` should be false by default and not have an effect. But maybe the url function is causing it as it gets a new identity on every render.

Try:
```
// Top level scope of your file
const getIframeUrl = (doc: SanityDocument) => getUrl(doc)

S.view
  .component(Iframe)
  .options({
    url: getIframeUrl,
    showDisplayUrl: false,
    reload: {
      button: true,
    },
  })
  .title('Preview')
```

**Comment by techsev** [comment]
I'm having the same issue, not sure what changed recently.

**Comment by stipsan** [comment]
Closing, the new API will call the `url` function on every change, and if the returned URL changes it'll trigger a reload.

So to preserve the old behavior:

```ts
S.view
  .component(Iframe)
  .options({
    url: (doc: SanityDocument) => `${getUrl(doc)}?rev=${doc?._rev}`,
    showDisplayUrl: false,
    reload: {
      button: true,
    },
  })
  .title('Preview')
```
