### ISSUE TITLE
V3 Example?

### ISSUE THREAD

**Issue by selbekk** [sanity-io/sanity-plugin-iframe-pane#9]
Hi! 

I'm testing out the Sanity Studio V3 (and your v3 branch), and I couldn't get it to work following your example. It looks a bit like the code example is from v2? Do you have a suggestion as to how this can be implemented in V3?

**Comment by simonpeters** [comment]
Yeah I'm also running into this.

https://beta.sanity.io/docs/platform/studio/v2-to-v3/prod-url-resolver

This should be the new to implement it. But not sure how to use in combination with this plugin.

**Comment by antonioortegajr** [comment]
Bumping this issue as the README in pull https://github.com/sanity-io/sanity-plugin-iframe-pane/pull/12 was SUPER helpful!
